NameTuple = ("Vivake", "Raj","Sunil","Ajith","Abdul")
NumberTuple = (1,2,3,4,5,1,2,6,1,4,6,3,1,2,3,1,3)
MixTuple = ('a',"DataBase",1,1.34,[8,9,10])
print()
print("Accessing whole Tuple ")
print(NameTuple)
print(NumberTuple)
print(MixTuple)
print()
print("Accessing elements of  Tuple ")
print(NameTuple[3])
print(NumberTuple[0])
print(NameTuple[-1])
print(MixTuple[1])
